name: Build & Deploy Spring App
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Spring App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Run Unit Tests
        run: mvn -B test --file pom.xml
        
      - name: Build app
        run: |
          mvn clean
          mvn -B package --file pom.xml
          
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerFile: Dockerfile
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/springboot-microservices:latest
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
          
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          

          
      
