name: build & deploy spring app
on:
 push:
  branches:
  - main
  
jobs:
  build-deploy:
   name: build & deploy spring app
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: setup JDK 17
       uses: actions/setup-java@v4
       with:
        distribution: 'corretto'
        java-version: 17
        
     - name: unit test
       run: mvn clean

     

  		 
  
  